$(document).ready(function(){
    $(".gallery").hide();
    $("#hide").click(function(){
        $(".gallery").fadeOut("slow")();
    });
    $("#show").click(function(){
        $(".gallery").fadeIn('slow');
    });
});
